In [1]:
#importing necessary libraries
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import *
from tensorflow.keras.models import *
import numpy as np
from sklearn.preprocessing import LabelEncoder




In [2]:
#getting the required dataset
dataset=pd.read_csv(r"C:\Users\HP PC\Downloads\data.csv")
dataset

message  fingers tail   species
0                                   pluvia arbor aquos        4   no    Aquari
1                            cosmix xeno nebuz odbitaz        5  yes   Zorblax
2                   solarix glixx novum galaxum quasar        5  yes   Zorblax
3             arbor insectus pesros ekos dootix nimbus        2  yes   Florian
4                    mermax drakos lorix epikoz deftax        4   no    Faerix
..                                                 ...      ...  ...       ...
495  empathix sadix disgux dredax pridius afgstix e...        2   no  Emotivor
496                      quasar ustron nebulax meteorn        4   no   Quixnar
497                 astron xeno ceaestar astron kometa        6  yes   Zorblax
498  sporzom nimbus terram terranix aviana ekos nimbub        2  yes   Florian
499     blastix titanos relikum drakos gryphox sirenix        4  yes   Mythron

[500 rows x 4 columns]

In [4]:
# First Model (Predicting species Based on fingers and tails)


In [5]:
#creating output label
Y=dataset["species"]
Y

0        Aquari
1       Zorblax
2       Zorblax
3       Florian
4        Faerix
         ...   
495    Emotivor
496     Quixnar
497     Zorblax
498     Florian
499     Mythron
Name: species, Length: 500, dtype: object

In [6]:
#creating input label
X=dataset.drop(["message","species"],axis=1)
X

fingers tail
0          4   no
1          5  yes
2          5  yes
3          2  yes
4          4   no
..       ...  ...
495        2   no
496        4   no
497        6  yes
498        2  yes
499        4  yes

[500 rows x 2 columns]

In [7]:
#one-hot-encoding tail variable and converting into integer for model
X = pd.get_dummies(X, columns=["tail"])
X=X.astype(int)
X

fingers  tail_no  tail_yes
0          4        1         0
1          5        0         1
2          5        0         1
3          2        0         1
4          4        1         0
..       ...      ...       ...
495        2        1         0
496        4        1         0
497        6        0         1
498        2        0         1
499        4        0         1

[500 rows x 3 columns]

In [8]:
#labelling 10 species from 0-10 to use softmax

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the Y labels automatically
Y = label_encoder.fit_transform(Y)

# Print the encoded labels and corresponding classes
print("Encoded Labels: ", Y)
print("Classes: ", label_encoder.classes_)  # Shows the mapping

Encoded Labels:  [0 9 9 4 3 6 6 5 2 8 2 2 6 4 6 5 4 0 6 4 8 7 1 0 5 8 7 7 6 6 9 8 6 8 9 6 2
 8 9 1 5 2 6 0 4 6 5 1 9 0 7 3 9 0 1 5 0 8 7 2 3 1 6 7 8 4 9 4 2 9 3 4 2 5
 5 7 4 9 7 3 7 9 7 0 3 5 7 1 8 0 7 9 7 3 1 9 6 2 6 1 5 3 8 9 9 4 7 1 8 3 2
 8 6 7 3 2 7 5 2 1 7 2 9 7 7 7 2 2 5 4 8 9 7 1 1 4 2 0 6 1 2 0 5 1 7 5 7 7
 7 2 2 2 4 4 8 3 1 9 1 3 3 6 7 6 7 5 9 1 8 3 2 4 4 8 0 9 6 1 1 8 9 3 7 2 7
 6 2 3 7 4 0 0 6 4 4 6 9 1 2 5 9 7 4 1 2 8 3 1 0 4 0 1 3 6 8 7 1 2 4 1 2 2
 0 0 5 9 9 9 9 9 9 2 9 3 1 3 3 4 3 5 5 8 7 8 7 2 9 2 3 4 6 5 1 4 4 9 2 0 5
 4 6 5 7 0 0 6 8 0 5 8 2 7 3 9 3 5 7 2 1 3 1 3 8 0 4 8 8 0 7 4 9 6 8 0 0 7
 2 1 6 2 6 2 1 4 4 0 0 8 2 6 1 7 9 2 2 3 5 5 4 5 7 6 2 4 7 0 4 2 1 3 8 8 8
 9 8 6 3 6 5 7 7 4 3 5 5 1 5 1 9 5 4 5 0 6 9 6 3 7 0 0 4 3 8 8 0 8 4 6 1 3
 0 0 0 9 8 9 0 9 8 7 4 2 5 5 1 5 2 8 5 4 2 6 8 5 9 5 1 4 5 4 8 0 4 7 7 1 3
 1 2 8 4 7 3 6 3 1 9 2 5 5 9 4 9 1 7 0 1 0 0 1 0 7 4 7 0 4 9 7 1 0 5 2 1 5
 6 9 5 7 0 7 7 8 3 3 7 1 0 4 9 4 2 3 2 6 4 3 1 8 7 4 9 1 0 9 5 1 3 7 5 1 1
 5 2 1 1

In [9]:
model = tf.keras.Sequential([
    Dense(1024, activation='relu', input_shape=(3,), kernel_regularizer=tf.keras.regularizers.l2(0.001)),
    BatchNormalization(),
   Dense(512, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
     BatchNormalization(),
    Dense(256, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
     BatchNormalization(),
    Dense(128, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
     BatchNormalization(),
    Dense(64, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
     BatchNormalization(),
    Dense(32,activation="relu",kernel_regularizer=tf.keras.regularizers.l2(0.001)),
     BatchNormalization(),
    Dense(10,activation="linear")  
])

#softmax loss with Adam optimization
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.summary()


C:\Users\HP PC\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 1024)                │           4,096 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ (None, 1024)                │           4,096 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 512)                 │         524,800 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_1                │ (None, 512)                 │           2,048 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 256)                 │         131,328 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_2                │ (None, 256)                 │           1,024 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 128)                 │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_3                │ (None, 128)                 │             512 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_4                │ (None, 64)                  │             256 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_5                │ (None, 32)                  │             128 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 10)                  │             330 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 711,850 (2.72 MB)

 Trainable params: 707,818 (2.70 MB)

 Non-trainable params: 4,032 (15.75 KB)

In [18]:
history = model.fit(X, Y, epochs=500, batch_size=100, validation_split=0.2)


Epoch 1/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.3293 - loss: 2.2666 - val_accuracy: 0.2100 - val_loss: 2.6128
Epoch 2/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.3400 - loss: 2.2477 - val_accuracy: 0.2000 - val_loss: 2.5865
Epoch 3/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.3450 - loss: 2.2534 - val_accuracy: 0.2100 - val_loss: 2.5667
Epoch 4/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.3440 - loss: 2.2344 - val_accuracy: 0.2100 - val_loss: 2.5525
Epoch 5/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.3130 - loss: 2.2421 - val_accuracy: 0.2100 - val_loss: 2.5507
Epoch 6/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.3213 - loss: 2.2459 - val_accuracy: 0.2100 - val_loss: 2.5607
Epoch 7/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.3300 - loss: 2.2259 - val_accuracy: 0.2100 - val_loss: 2.5526
Epoch 8/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.3217 - loss: 2.2181 - val_accuracy: 0.2100 - val_loss:

In [20]:

answer=model.predict(X)
answer

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


array([[ 1.8251636 , -0.8336298 , -1.5621748 , ...,  3.16535   ,
         1.0595335 ,  1.3997983 ],
       [-0.09905979, -4.3234496 , -4.208604  , ...,  0.9330719 ,
         1.707015  ,  1.472486  ],
       [-0.09905979, -4.3234496 , -4.208604  , ...,  0.9330719 ,
         1.707015  ,  1.472486  ],
       ...,
       [-0.66892684, -3.9983742 , -3.1843383 , ...,  0.7143807 ,
         1.781366  ,  1.7416741 ],
       [-3.8753052 , -0.6969232 ,  5.246046  , ..., -1.282541  ,
         3.0336404 , -3.3786416 ],
       [ 0.24598211, -3.7320137 , -3.5478618 , ...,  0.5170696 ,
         0.99658775,  0.71802217]], dtype=float32)

In [21]:
#get the list of probabilities for each species corresponding to a set of 
final_answer=tf.nn.softmax(answer)
final_answer

<tf.Tensor: shape=(500, 10), dtype=float32, numpy=
array([[1.0859051e-01, 7.6048831e-03, 3.6701979e-03, ..., 4.1478920e-01,
        5.0499026e-02, 7.0967279e-02],
       [3.4549396e-02, 5.0560490e-04, 5.6713726e-04, ..., 9.6981652e-02,
        2.1028525e-01, 1.6632371e-01],
       [3.4549396e-02, 5.0560490e-04, 5.6713726e-04, ..., 9.6981652e-02,
        2.1028525e-01, 1.6632371e-01],
       ...,
       [1.7715162e-02, 6.3443102e-04, 1.4319099e-03, ..., 7.0649303e-02,
        2.0534953e-01, 1.9735846e-01],
       [6.5751148e-05, 1.5785457e-03, 6.0152805e-01, ..., 8.7887369e-04,
        6.5829456e-02, 1.0804430e-04],
       [8.2375064e-02, 1.5423186e-03, 1.8541733e-03, ..., 1.0802582e-01,
        1.7449366e-01, 1.3206880e-01]], dtype=float32)>

In [22]:
dict={}
for i in range(500):
    row = tuple(X.iloc[i].tolist())
    
    if row in dict:
        pass
    else:
        dict[row]=final_answer[i]
dict

        

{(4,
  1,
  0): <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([0.10859051, 0.00760488, 0.0036702 , 0.25992653, 0.05691622,
        0.00117666, 0.02585957, 0.4147892 , 0.05049903, 0.07096728],
       dtype=float32)>,
 (5,
  0,
  1): <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([0.0345494 , 0.0005056 , 0.00056714, 0.00691472, 0.13567483,
        0.16910042, 0.17909732, 0.09698165, 0.21028525, 0.1663237 ],
       dtype=float32)>,
 (2,
  0,
  1): <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([6.5751279e-05, 1.5785480e-03, 6.0152805e-01, 8.8495197e-04,
        2.0931697e-01, 9.8102109e-04, 1.1882825e-01, 8.7887538e-04,
        6.5829471e-02, 1.0804430e-04], dtype=float32)>,
 (3,
  1,
  0): <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([0.19763035, 0.2289361 , 0.07800111, 0.22610353, 0.03647914,
        0.0044125 , 0.04495053, 0.13006727, 0.03731481, 0.01610466],
       dtype=float32)>,
 (6,
  0,
  1): <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([0.

In [17]:
len(dict.keys())

19

In [19]:
#model 2 (based crudely on messages)


In [29]:

df = np.array(dataset)
dic = {}
for i in df:
    msg = i[0].split()
    for word in msg:
        if word not in dic:
            dic[word]={i[3]:1}
        else:
            dic[word][i[3]] = dic[word].get(i[3],0) + 1
for word in dic:
    occurences = sum([dic[word][i] for i in dic[word]])
    for species in dic[word]:
        dic[word][species]/=occurences

print(dic)

{'pluvia': {'Aquari': 0.5, 'Florian': 0.5}, 'arbor': {'Aquari': 0.625, 'Florian': 0.375}, 'aquos': {'Aquari': 0.5714285714285714, 'Florian': 0.42857142857142855}, 'cosmix': {'Zorblax': 0.6086956521739131, 'Quixnar': 0.391304347826087}, 'xeno': {'Zorblax': 0.3888888888888889, 'Quixnar': 0.6111111111111112}, 'nebuz': {'Zorblax': 0.48, 'Quixnar': 0.52}, 'odbitaz': {'Zorblax': 1.0}, 'solarix': {'Zorblax': 0.44, 'Quixnar': 0.56}, 'glixx': {'Zorblax': 0.6190476190476191, 'Quixnar': 0.38095238095238093}, 'novum': {'Zorblax': 0.5454545454545454, 'Quixnar': 0.45454545454545453}, 'galaxum': {'Zorblax': 0.3684210526315789, 'Quixnar': 0.631578947368421}, 'quasar': {'Zorblax': 0.44, 'Quixnar': 0.56}, 'insectus': {'Florian': 0.7857142857142857, 'Aquari': 0.21428571428571427}, 'pesros': {'Florian': 1.0}, 'ekos': {'Florian': 0.5, 'Aquari': 0.5}, 'dootix': {'Florian': 1.0}, 'nimbus': {'Florian': 0.75, 'Aquari': 0.25}, 'mermax': {'Faerix': 0.4375, 'Mythron': 0.5625}, 'drakos': {'Faerix': 0.6923076923076

In [30]:
sure_dict={}
for key, sub_dict in dic.items():
    # Check if any probability is exactly 1.0
    for sub_key, prob in sub_dict.items():
        if prob == 1.0:
            sure_dict[key] = sub_key
            break 

sure_dict



{'odbitaz': 'Zorblax',
 'pesros': 'Florian',
 'dootix': 'Florian',
 'deftax': 'Faerix',
 'digitvon': 'Nexoon',
 'sagaq': 'Mythron',
 'angxtix': 'Sentire',
 'crypooz': 'Nexoon',
 'tkchnos': 'Nexoon',
 'quaztaz': 'Nexoon',
 'fsunar': 'Florian',
 'nexhs': 'Nexoon',
 'circum': 'Nexoon',
 'ghamex': 'Sentire',
 'novtm': 'Quixnar',
 'euvex': 'Mythron',
 'magit': 'Mythron',
 'ftbulon': 'Mythron',
 'blaloz': 'Quixnar',
 'yircux': 'Nexoon',
 'pulsoo': 'Zorblax',
 'tobonix': 'Nexoon',
 'technoc': 'Nexoon',
 'empnthix': 'Sentire',
 'ueox': 'Zorblax',
 'nivara': 'Zorblax',
 'hechan': 'Nexoon',
 'technds': 'Nexoon',
 'quagtix': 'Nexoon',
 'lazxron': 'Nexoon',
 'gyixx': 'Zorblax',
 'neulaz': 'Cybex',
 'sagau': 'Mythron',
 'qexus': 'Nexoon',
 'chrcux': 'Nexoon',
 'izsectus': 'Florian',
 'biokex': 'Nexoon',
 'novafa': 'Zorblax',
 'pclsox': 'Zorblax',
 'xene': 'Zorblax',
 'meteoen': 'Zorblax',
 'solarih': 'Quixnar',
 'rnlikum': 'Faerix',
 'tenix': 'Faerix',
 'ialaxum': 'Zorblax',
 'cixcux': 'Cybex',
 'n

In [31]:
len(sure_dict.keys())

505

In [ ]:
#for the final solution we can first of all take a look at individual words in the message and if the word mathes one of 
#those in sure_dict we can claim to have found the species(100 percent probability)

