In [ ]:
#importing necessary libraries
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import *
from tensorflow.keras.models import *
import numpy as np
from sklearn.preprocessing import LabelEncoder




In [ ]:
#getting the required dataset
dataset=pd.read_csv(r"C:\Users\HP PC\Downloads\data.csv")
dataset

message  fingers tail   species
0                                   pluvia arbor aquos        4   no    Aquari
1                            cosmix xeno nebuz odbitaz        5  yes   Zorblax
2                   solarix glixx novum galaxum quasar        5  yes   Zorblax
3             arbor insectus pesros ekos dootix nimbus        2  yes   Florian
4                    mermax drakos lorix epikoz deftax        4   no    Faerix
..                                                 ...      ...  ...       ...
495  empathix sadix disgux dredax pridius afgstix e...        2   no  Emotivor
496                      quasar ustron nebulax meteorn        4   no   Quixnar
497                 astron xeno ceaestar astron kometa        6  yes   Zorblax
498  sporzom nimbus terram terranix aviana ekos nimbub        2  yes   Florian
499     blastix titanos relikum drakos gryphox sirenix        4  yes   Mythron

[500 rows x 4 columns]

In [ ]:
# First Model (Predicting species Based on fingers and tails)


In [ ]:
#extracting the message column from dataset and storing in X_messages
X_messages=dataset["message"]
X_messages

0                                     pluvia arbor aquos
1                              cosmix xeno nebuz odbitaz
2                     solarix glixx novum galaxum quasar
3               arbor insectus pesros ekos dootix nimbus
4                      mermax drakos lorix epikoz deftax
                             ...                        
495    empathix sadix disgux dredax pridius afgstix e...
496                        quasar ustron nebulax meteorn
497                   astron xeno ceaestar astron kometa
498    sporzom nimbus terram terranix aviana ekos nimbub
499       blastix titanos relikum drakos gryphox sirenix
Name: message, Length: 500, dtype: object

In [ ]:
#creating output label have species column
Y_species=dataset["species"]
Y_species

0        Aquari
1       Zorblax
2       Zorblax
3       Florian
4        Faerix
         ...   
495    Emotivor
496     Quixnar
497     Zorblax
498     Florian
499     Mythron
Name: species, Length: 500, dtype: object

In [ ]:
#creating input label for the first part of the model (fingers+tail)
X=dataset.drop(["message","species"],axis=1)
X

fingers tail
0          4   no
1          5  yes
2          5  yes
3          2  yes
4          4   no
..       ...  ...
495        2   no
496        4   no
497        6  yes
498        2  yes
499        4  yes

[500 rows x 2 columns]

In [ ]:
#one-hot-encoding tail variable and converting into integer for model
X = pd.get_dummies(X, columns=["tail"])
X=X.astype(int)
X

fingers  tail_no  tail_yes
0          4        1         0
1          5        0         1
2          5        0         1
3          2        0         1
4          4        1         0
..       ...      ...       ...
495        2        1         0
496        4        1         0
497        6        0         1
498        2        0         1
499        4        0         1

[500 rows x 3 columns]

In [ ]:
#labelling 10 species from 0-10 to use softmax

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the Y labels automatically
Y = label_encoder.fit_transform(Y_species)
species_mapping = dict (zip(label_encoder.classes_, range(len(label_encoder.classes_))))

# Print the encoded labels and corresponding classes
print("Encoded Labels: ", Y)
print("Classes: ", label_encoder.classes_)  # Shows the mapping
print(species_mapping)

Encoded Labels:  [0 9 9 4 3 6 6 5 2 8 2 2 6 4 6 5 4 0 6 4 8 7 1 0 5 8 7 7 6 6 9 8 6 8 9 6 2
 8 9 1 5 2 6 0 4 6 5 1 9 0 7 3 9 0 1 5 0 8 7 2 3 1 6 7 8 4 9 4 2 9 3 4 2 5
 5 7 4 9 7 3 7 9 7 0 3 5 7 1 8 0 7 9 7 3 1 9 6 2 6 1 5 3 8 9 9 4 7 1 8 3 2
 8 6 7 3 2 7 5 2 1 7 2 9 7 7 7 2 2 5 4 8 9 7 1 1 4 2 0 6 1 2 0 5 1 7 5 7 7
 7 2 2 2 4 4 8 3 1 9 1 3 3 6 7 6 7 5 9 1 8 3 2 4 4 8 0 9 6 1 1 8 9 3 7 2 7
 6 2 3 7 4 0 0 6 4 4 6 9 1 2 5 9 7 4 1 2 8 3 1 0 4 0 1 3 6 8 7 1 2 4 1 2 2
 0 0 5 9 9 9 9 9 9 2 9 3 1 3 3 4 3 5 5 8 7 8 7 2 9 2 3 4 6 5 1 4 4 9 2 0 5
 4 6 5 7 0 0 6 8 0 5 8 2 7 3 9 3 5 7 2 1 3 1 3 8 0 4 8 8 0 7 4 9 6 8 0 0 7
 2 1 6 2 6 2 1 4 4 0 0 8 2 6 1 7 9 2 2 3 5 5 4 5 7 6 2 4 7 0 4 2 1 3 8 8 8
 9 8 6 3 6 5 7 7 4 3 5 5 1 5 1 9 5 4 5 0 6 9 6 3 7 0 0 4 3 8 8 0 8 4 6 1 3
 0 0 0 9 8 9 0 9 8 7 4 2 5 5 1 5 2 8 5 4 2 6 8 5 9 5 1 4 5 4 8 0 4 7 7 1 3
 1 2 8 4 7 3 6 3 1 9 2 5 5 9 4 9 1 7 0 1 0 0 1 0 7 4 7 0 4 9 7 1 0 5 2 1 5
 6 9 5 7 0 7 7 8 3 3 7 1 0 4 9 4 2 3 2 6 4 3 1 8 7 4 9 1 0 9 5 1 3 7 5 1 1
 5 2 1 1

In [ ]:
# Define a deep neural network for species prediction based on fingers and tail data
model = tf.keras.Sequential([
    Dense(1024, activation='relu', input_shape=(3,), kernel_regularizer=tf.keras.regularizers.l2(0.001)),
    BatchNormalization(),
   Dense(512, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
     BatchNormalization(),
    Dense(256, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
     BatchNormalization(),
    Dense(128, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
     BatchNormalization(),
    Dense(64, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
     BatchNormalization(),
    Dense(32,activation="relu",kernel_regularizer=tf.keras.regularizers.l2(0.001)),
     BatchNormalization(),
    Dense(10,activation="linear")
])

# Compile the model using the Adam optimizer and sparse categorical cross-entropy loss
# Sparse categorical cross-entropy is used since Y is label encoded (integer labels)
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.summary()


C:\Users\HP PC\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 1024)                │           4,096 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ (None, 1024)                │           4,096 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 512)                 │         524,800 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_1                │ (None, 512)                 │           2,048 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 256)                 │         131,328 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_2                │ (None, 256)                 │           1,024 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 128)                 │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_3                │ (None, 128)                 │             512 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_4                │ (None, 64)                  │             256 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_5                │ (None, 32)                  │             128 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 10)                  │             330 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 711,850 (2.72 MB)

 Trainable params: 707,818 (2.70 MB)

 Non-trainable params: 4,032 (15.75 KB)

In [ ]:
# Train the model using the input data X (fingers + tail) and output labels Y (species)
# We use 20% of the data for validation, with 500 epochs and a batch size of 100
history = model.fit(X, Y, epochs=500, batch_size=100, validation_split=0.2)


Epoch 1/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 6s 169ms/step - accuracy: 0.1230 - loss: 4.0558 - val_accuracy: 0.0800 - val_loss: 3.5809
Epoch 2/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.2377 - loss: 3.3141 - val_accuracy: 0.0900 - val_loss: 3.5411
Epoch 3/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.2443 - loss: 3.1421 - val_accuracy: 0.1400 - val_loss: 3.5076
Epoch 4/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.3200 - loss: 3.0293 - val_accuracy: 0.1600 - val_loss: 3.4857
Epoch 5/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.3133 - loss: 3.0031 - val_accuracy: 0.1400 - val_loss: 3.4763
Epoch 6/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.3153 - loss: 2.9496 - val_accuracy: 0.0900 - val_loss: 3.4680
Epoch 7/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.3050 - loss: 2.8992 - val_accuracy: 0.0800 - val_loss: 3.4593
Epoch 8/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.3273 - loss: 2.8623 - val_accuracy: 0.0900 - val_loss

In [ ]:
# Predicting the species based on the input data (fingers + tail)
answer=model.predict(X)
answer

16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step


array([[ 1.9187573 , -1.3617636 , -1.6896837 , ...,  2.803007  ,
         0.7766609 ,  1.1007001 ],
       [-0.02186597, -2.9889383 , -3.2085245 , ...,  1.2267001 ,
         1.9949011 ,  1.5609689 ],
       [-0.02186597, -2.9889383 , -3.2085245 , ...,  1.2267001 ,
         1.9949011 ,  1.5609689 ],
       ...,
       [-1.4534332 , -3.5546327 , -2.7028282 , ..., -0.67095804,
         2.6477427 ,  2.5593607 ],
       [-3.682248  ,  0.42963699,  4.0444684 , ..., -2.9130964 ,
         1.2989615 , -2.1909301 ],
       [ 0.124493  , -2.7162573 , -2.9212472 , ...,  0.44749686,
         1.0641721 ,  0.25257394]], dtype=float32)

In [ ]:
# Convert the output logits to probabilities using softmax
final_answer=tf.nn.softmax(answer)
final_answer

<tf.Tensor: shape=(500, 10), dtype=float32, numpy=
array([[1.5043779e-01, 5.6577637e-03, 4.0759700e-03, ..., 3.6423501e-01,
        4.8012111e-02, 6.6386424e-02],
       [3.0589551e-02, 1.5739462e-03, 1.2636447e-03, ..., 1.0661503e-01,
        2.2984968e-01, 1.4893253e-01],
       [3.0589551e-02, 1.5739462e-03, 1.2636447e-03, ..., 1.0661503e-01,
        2.2984968e-01, 1.4893253e-01],
       ...,
       [3.3973195e-03, 4.1552488e-04, 9.7393704e-04, ..., 7.4295239e-03,
        2.0523642e-01, 1.8787567e-01],
       [1.7506036e-04, 1.0689485e-02, 3.9706185e-01, ..., 3.7776885e-04,
        2.5497625e-02, 7.7778415e-04],
       [7.4121773e-02, 4.3273666e-03, 3.5253128e-03, ..., 1.0238223e-01,
        1.8968949e-01, 8.4250137e-02]], dtype=float32)>

In [ ]:
# Store unique input combinations (fingers + tail) with their corresponding predicted species probabilities
dicti={}
for i in range(500):
    row = tuple(X.iloc[i].tolist())

    if row in dicti:
        pass
    else:
        dicti[row]=final_answer[i]
dicti



{(4,
  1,
  0): <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([0.15043779, 0.00565776, 0.00407597, 0.27090698, 0.05687134,
        0.00217436, 0.03124221, 0.364235  , 0.04801211, 0.06638642],
       dtype=float32)>,
 (5,
  0,
  1): <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([0.03058955, 0.00157395, 0.00126364, 0.01225556, 0.14424051,
        0.14801733, 0.1766622 , 0.10661503, 0.22984968, 0.14893253],
       dtype=float32)>,
 (2,
  0,
  1): <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([1.7506037e-04, 1.0689491e-02, 3.9706171e-01, 1.8272857e-03,
        3.7007317e-01, 2.2141349e-03, 1.9130604e-01, 3.7776926e-04,
        2.5497645e-02, 7.7778427e-04], dtype=float32)>,
 (3,
  1,
  0): <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([0.2139856 , 0.14195888, 0.07484508, 0.26902995, 0.02720961,
        0.00314814, 0.06362137, 0.15739183, 0.0326355 , 0.01617401],
       dtype=float32)>,
 (6,
  0,
  1): <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([0.

In [ ]:
len(dicti.keys())

19

In [ ]:
# Model 2 (Predicting species based on message content)


In [ ]:
# Initialize a dictionary to store word-level probabilities for each species based on message content
df = np.array(dataset)
dic = {}
for i in df:
    msg = i[0].split()
    for word in msg:
        if word not in dic:
            dic[word]={i[3]:1}
        else:
            dic[word][i[3]] = dic[word].get(i[3],0) + 1
# Normalize the probabilities for each word by dividing by total occurrences of the word
for word in dic:
    occurences = sum([dic[word][i] for i in dic[word]])
    for species in dic[word]:
        dic[word][species]/=occurences

print(dic)

{'pluvia': {'Aquari': 0.5, 'Florian': 0.5}, 'arbor': {'Aquari': 0.625, 'Florian': 0.375}, 'aquos': {'Aquari': 0.5714285714285714, 'Florian': 0.42857142857142855}, 'cosmix': {'Zorblax': 0.6086956521739131, 'Quixnar': 0.391304347826087}, 'xeno': {'Zorblax': 0.3888888888888889, 'Quixnar': 0.6111111111111112}, 'nebuz': {'Zorblax': 0.48, 'Quixnar': 0.52}, 'odbitaz': {'Zorblax': 1.0}, 'solarix': {'Zorblax': 0.44, 'Quixnar': 0.56}, 'glixx': {'Zorblax': 0.6190476190476191, 'Quixnar': 0.38095238095238093}, 'novum': {'Zorblax': 0.5454545454545454, 'Quixnar': 0.45454545454545453}, 'galaxum': {'Zorblax': 0.3684210526315789, 'Quixnar': 0.631578947368421}, 'quasar': {'Zorblax': 0.44, 'Quixnar': 0.56}, 'insectus': {'Florian': 0.7857142857142857, 'Aquari': 0.21428571428571427}, 'pesros': {'Florian': 1.0}, 'ekos': {'Florian': 0.5, 'Aquari': 0.5}, 'dootix': {'Florian': 1.0}, 'nimbus': {'Florian': 0.75, 'Aquari': 0.25}, 'mermax': {'Faerix': 0.4375, 'Mythron': 0.5625}, 'drakos': {'Faerix': 0.6923076923076

In [ ]:
# Extract words that are 100% associated with a single species (sure match)
sure_dict={}
for key, sub_dict in dic.items():
    # Check if any probability is exactly 1.0
    for sub_key, prob in sub_dict.items():
        if prob == 1.0:
            sure_dict[key] = sub_key
            break

sure_dict



{'odbitaz': 'Zorblax',
 'pesros': 'Florian',
 'dootix': 'Florian',
 'deftax': 'Faerix',
 'digitvon': 'Nexoon',
 'sagaq': 'Mythron',
 'angxtix': 'Sentire',
 'crypooz': 'Nexoon',
 'tkchnos': 'Nexoon',
 'quaztaz': 'Nexoon',
 'fsunar': 'Florian',
 'nexhs': 'Nexoon',
 'circum': 'Nexoon',
 'ghamex': 'Sentire',
 'novtm': 'Quixnar',
 'euvex': 'Mythron',
 'magit': 'Mythron',
 'ftbulon': 'Mythron',
 'blaloz': 'Quixnar',
 'yircux': 'Nexoon',
 'pulsoo': 'Zorblax',
 'tobonix': 'Nexoon',
 'technoc': 'Nexoon',
 'empnthix': 'Sentire',
 'ueox': 'Zorblax',
 'nivara': 'Zorblax',
 'hechan': 'Nexoon',
 'technds': 'Nexoon',
 'quagtix': 'Nexoon',
 'lazxron': 'Nexoon',
 'gyixx': 'Zorblax',
 'neulaz': 'Cybex',
 'sagau': 'Mythron',
 'qexus': 'Nexoon',
 'chrcux': 'Nexoon',
 'izsectus': 'Florian',
 'biokex': 'Nexoon',
 'novafa': 'Zorblax',
 'pclsox': 'Zorblax',
 'xene': 'Zorblax',
 'meteoen': 'Zorblax',
 'solarih': 'Quixnar',
 'rnlikum': 'Faerix',
 'tenix': 'Faerix',
 'ialaxum': 'Zorblax',
 'cixcux': 'Cybex',
 'n

In [ ]:
len(sure_dict.keys())

505

In [ ]:
#For the final solution, we can first analyze individual words in the message, and if a word matches one in the sure_dict,
#we can confidently claim to have identified the species with 100% probability.



In [ ]:
#Get the labelling for the species
species_mapping

{'Aquari': 0,
 'Cybex': 1,
 'Emotivor': 2,
 'Faerix': 3,
 'Florian': 4,
 'Mythron': 5,
 'Nexoon': 6,
 'Quixnar': 7,
 'Sentire': 8,
 'Zorblax': 9}

In [ ]:
# Helper function to get message-based probabilities for species prediction
def get_message_probabilities(message, dic,species_mapping):
    words = message.split()
    species_prob = np.zeros(10)  # Initialize an array for 10 species (size 10 because you have 10 species)

    for word in words:
        if word in dic:
            for species_label in dic[word]:
                species_index=species_mapping[species_label]


                species_prob[species_index] += dic[word][species_label]  # Add probabilities for each species



    return species_prob/np.sum(species_prob)


# Helper function to get finger/tail-based probabilities
def get_finger_tail_probabilities(X_row, dict):
    X_tuple = tuple(X_row)
    if X_tuple in dict:
        return dict[X_tuple]
    else:
        return np.ones(10) / 10  # Return uniform probability if no match

# Combine message and finger/tail probabilities using weights alpha and beta
def combined_probability(message, X_row, dic, dicti, alpha=0.9, beta=0.1):
    message_prob = get_message_probabilities(message, dic,species_mapping)
    finger_tail_prob = get_finger_tail_probabilities(X_row, dicti)

    final_prob = np.power(message_prob,alpha) + np.power(finger_tail_prob,beta)
    return final_prob / np.sum(final_prob)  # Normalize to get probabilities



In [ ]:
# Example input
message = "cosmix xeno nebuz odbitaz"  # Test message
fingers = 5  # Test fingers value
X_row=[5,0,1]


# Fetch probabilities from the combined model
def predict_species_test(message, X_row, dic, dicti, species_mapping):
    # Get probabilities from the message
    message_prob = get_message_probabilities(message, dic,species_mapping )

    # Get probabilities from finger/tail data
    finger_tail_prob = get_finger_tail_probabilities(X_row, dicti)

    # Use the combined model to compute the final probabilities
    #alpha beta found out after manual hit and trial
    final_prob = combined_probability(message, X_row, dic, dicti, alpha=0.92, beta=0.08)

    # Find the species with the highest probability (argmax)
    predicted_species_index = np.argmax(final_prob)

    # Return the predicted species label using label_encoder
    return predicted_species_index

# Test the model with the input provided
predicted_species_index = predict_species_test(message, X_row, dic, dicti,species_mapping)
predicted_species_index



9

In [ ]:
##Checking the accuracy
import pandas as pd
import numpy as np

# X_messages, X, Y are the DataFrames defined before
# X_messages = pd.DataFrame({'messages': ['message1', 'message2', ...]})
# X = pd.DataFrame({'fingers': [5, 0, 1, ...], 'tails': [...]})
# Y = pd.Series([...])  # True labels

# Initialize a list to hold predictions
predictions = []

# Iterate through the DataFrames
for i in range(len(X_messages)):
    message = X_messages.iloc[i]
    X_row = X.iloc[i].values  # Convert to array if needed
    predicted_species_index = predict_species_test(message, X_row, dic, dicti, species_mapping)
    predictions.append(predicted_species_index)

# Convert predictions to a DataFrame for easier comparison
predictions_df = pd.DataFrame({'Predicted': predictions, 'Actual': Y})

# Evaluate accuracy
accuracy = (predictions_df['Predicted'] == predictions_df['Actual']).mean()
print(f"Accuracy: {accuracy * 100:.2f}%")

# Optionally, inspect predictions
print(predictions_df)


Accuracy: 96.40%
     Predicted  Actual
0            0       0
1            9       9
2            7       9
3            4       4
4            3       3
..         ...     ...
495          2       2
496          7       7
497          9       9
498          4       4
499          5       5

[500 rows x 2 columns]


In [ ]:
#Testing the model

In [ ]:
message = "iephyr terram nimbus terram faunar foliar"  # Test message
fingers = 2  # Test fingers value
X_row=[2,0,1]

predict_species=predict_species_test(message, X_row, dic, dicti,species_mapping)
answer = label_encoder.inverse_transform([predict_species])[0]
print(answer)




Florian


In [ ]:
#correct prediction according to our analysis

In [ ]:
#more test cases
message = "cjbrex natobyt synapz biotex nanobyt"  # Test message
fingers = 2  # Test fingers value
X_row=[2,1,0]

predict_species=predict_species_test(message, X_row, dic, dicti,species_mapping)
answer = label_encoder.inverse_transform([predict_species])[0]
print(answer)
print(predict_species)




Cybex
1


In [ ]:
#getting result.csv

In [ ]:
X_test=pd.read_csv(r"C:\Users\HP PC\Downloads\test (1).csv")
X_test

message  fingers tail
0            iephyr terram nimbus terram faunar foliar        2   no
1           joyzor uleex luvium caloox shockus blissae        4  yes
2                                   aquos arbor ventuc        4  yes
3     nympha nympha epikoz nympha mythox mythox mythox        3   no
4                               diitax sibenix fabulon        4  yes
..                                                 ...      ...  ...
294              fabuion drakos lorix relikum cyclopix        4  yes
295   codex cybrex algorix synapz mechan nanozom dotax        5  yes
296                      centarex mythox nympha krakos        3  yes
297  orbitaz astron glixx novara novrm ufox qcasar ...        3   no
298               blissam sorrowz blissam fearix sadix        2   no

[299 rows x 3 columns]

In [ ]:
#Creating the X_test and X_test_rows dataframes
X_test_messages=X_test["message"]
X_test_rows=X_test.drop("message",axis=1)

In [ ]:
import pandas as pd
import numpy as np

# X_messages, X, Y are the DataFrames
# X_messages = pd.DataFrame({'messages': ['message1', 'message2', ...]})
# X = pd.DataFrame({'fingers': [5, 0, 1, ...], 'tails': [...]})
# Y = pd.Series([...])  # True labels

# Initialize a list to hold predictions
predictions = []

# Iterate through the DataFrames
for i in range(len(X_test_messages)):
    message = X_test_messages.iloc[i]
    X_row = X_test_rows.iloc[i].values  # Convert to array if needed
    predicted_species_index = predict_species_test(message, X_row, dic, dicti, species_mapping)
    predictions.append(predicted_species_index)

predictions


[4,
 2,
 0,
 5,
 3,
 3,
 3,
 5,
 2,
 0,
 5,
 2,
 7,
 9,
 5,
 0,
 4,
 1,
 4,
 0,
 7,
 2,
 7,
 1,
 5,
 1,
 4,
 2,
 2,
 5,
 1,
 2,
 5,
 2,
 5,
 2,
 4,
 4,
 4,
 7,
 8,
 7,
 5,
 1,
 0,
 2,
 7,
 7,
 9,
 4,
 2,
 9,
 2,
 7,
 2,
 2,
 2,
 2,
 5,
 1,
 1,
 1,
 5,
 2,
 2,
 5,
 2,
 5,
 1,
 9,
 9,
 2,
 2,
 7,
 2,
 2,
 1,
 5,
 1,
 8,
 2,
 1,
 2,
 4,
 6,
 2,
 3,
 9,
 1,
 3,
 2,
 5,
 1,
 9,
 2,
 4,
 5,
 1,
 2,
 5,
 4,
 2,
 2,
 0,
 1,
 9,
 4,
 2,
 9,
 2,
 2,
 3,
 4,
 3,
 0,
 3,
 5,
 6,
 5,
 9,
 5,
 2,
 1,
 4,
 7,
 4,
 1,
 4,
 7,
 9,
 1,
 9,
 5,
 0,
 8,
 8,
 1,
 8,
 1,
 5,
 1,
 2,
 4,
 2,
 7,
 0,
 2,
 5,
 4,
 1,
 0,
 1,
 0,
 2,
 0,
 2,
 4,
 2,
 4,
 2,
 2,
 0,
 1,
 1,
 1,
 2,
 4,
 6,
 3,
 1,
 5,
 2,
 7,
 2,
 1,
 2,
 0,
 8,
 4,
 8,
 2,
 9,
 4,
 5,
 5,
 4,
 2,
 1,
 1,
 9,
 2,
 7,
 3,
 7,
 1,
 1,
 5,
 5,
 4,
 1,
 1,
 5,
 2,
 0,
 5,
 1,
 5,
 4,
 7,
 3,
 5,
 3,
 7,
 1,
 0,
 2,
 0,
 3,
 1,
 1,
 0,
 2,
 1,
 2,
 0,
 2,
 2,
 5,
 0,
 1,
 5,
 9,
 4,
 5,
 5,
 5,
 1,
 7,
 3,
 7,
 7,
 1,
 5,
 2,
 9,
 0,
 4,
 8,
 0,
 4,


In [ ]:
# Convert predictions list to a DataFrame
predicted_species_names = [label_encoder.inverse_transform([pred])[0] for pred in predictions]


predictions_df = pd.DataFrame(predicted_species_names, columns=['Species'])

# Save the DataFrame to a CSV file
predictions_df.to_csv(r"C:\Users\HP PC\Downloads\result(2).csv", index=False)

# This will create a file named 'predictions.csv' in the current working directory
print("Predictions saved to result.csv")


Predictions saved to result.csv
